name: 'Bug Report'
title: '[Bug]: '
description: 'Report a bug to contribute to project improvement. Detail the issue you encountered to assist us in enhancing the functionality and reliability of our project.'
labels: ['bug']
projects: ['slurui/slur']
body:
  - type: 'markdown'
    attributes:
      value: |
        Thank you for creating an issue.
        Please search open/closed issues before submitting, as someone might have reported the same issue before.
        We're all volunteers here, so help us help you by accurately filling out this template.
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'Provide a brief description of the issue.'
      placeholder: |
        When I ____, I expected ____ to happen, but ____ happened instead.
    validations:
      required: true
  - type: 'input'
    id: 'reproduction'
    attributes:
      label: 'Link to Reproduction'
      description: 'Link to a CodeSandbox reproduction demonstrating the bug.'
      placeholder: 'https://codesandbox.io'
    validations:
      required: true
  - type: 'textarea'
    id: 'steps'
    attributes:
      label: 'Steps to Reproduce'
      description: 'Explain how to reproduce the issue in the provided reproduction.'
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
  - type: 'input'
    id: 'slur-version'
    attributes:
      label: 'slur Version'
      description: 'The version of slur you are using.'
      placeholder: '1.0.0'
    validations:
      required: true
  - type: 'input'
    id: 'browser'
    attributes:
      label: 'Browser'
      description: 'The browser(s) where this issue occurred.'
      placeholder: 'Google Chrome 93'
  - type: 'checkboxes'
    id: 'operating-system'
    attributes:
      label: 'Operating System'
      description: 'The operating system(s) where this issue occurred.'
      options:
        - label: 'macOS'
        - label: 'Windows'
        - label: 'Linux'
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: 'Provide any additional information, such as screenshots, notes, or links to related ideas.'
